# Generated by Django 4.1.6 on 2024-07-11 14:59

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=30)),
                ('mobile', models.CharField(default=None, max_length=10)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('username', models.CharField(default=None, max_length=30)),
                ('password', models.CharField(default=None, max_length=30)),
                ('confirm_password', models.CharField(default=None, max_length=30)),
                ('password_hash', models.CharField(default=None, max_length=30)),
            ],
        ),
    ]
