# Generated by Django 4.1.6 on 2024-08-02 02:51

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyRelationModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('firm_name', models.CharField(default=None, max_length=30)),
                ('firm_address', models.CharField(default=None, max_length=30)),
                ('account_id', models.CharField(default=None, max_length=30)),
                ('biz_identification_no', models.CharField(default=None, max_length=10)),
                ('others', models.CharField(default=None, max_length=30)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userlogin.consumermodel')),
            ],
        ),
    ]
